<a href="https://colab.research.google.com/github/tjwei/NCTU_Private_DeepLearning/blob/master/Secret_Sharing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Additive Secret Sharing

Most of the material taken from https://github.com/udacity/private-ai/blob/master/Section%203%20-%20Securing%20Federated%20Learning.ipynb and https://github.com/udacity/private-ai/blob/master/Section%204%20-%20Encrypted%20Deep%20Learning.ipynb

For more great information about SMPC protocols like this one, visit https://mortendahl.github.io. 

While being able to have a trusted third party is certainly nice, in an ideal setting we wouldn't have to trust anyone at all. This is where Cryptography can provide an interesting alterantive.

Specifically, we're going to be looking at a simple protocol for Secure Multi-Party Computation called Additive Secret Sharing. This protocol will allow multiple parties (of size 3 or more) to aggregate their gradients without the use of a trusted 3rd party to perform the aggregation. In other words, we can add 3 numbers together from 3 different people without anyone ever learning the inputs of any other actors.

Let's start by considering the number 5, which we'll put into a varible x

In [0]:
x = 5

Let's say we wanted to SHARE the ownership of this number between two people, Alice and Bob. We could split this number into two shares, 2, and 3, and give one to Alice and one to Bob

In [1]:
bob_x_share = 2
alice_x_share = 3

decrypted_x = bob_x_share + alice_x_share
decrypted_x

5

Note that neither Bob nor Alice know the value of x. They only know the value of their own SHARE of x. Thus, the true value of X is hidden (i.e., encrypted).

The truly amazing thing, however, is that Alice and Bob can still compute using this value! They can perform arithmetic over the hidden value! Let's say Bob and Alice wanted to multiply this value by 2! If each of them multiplied their respective share by 2, then the hidden number between them is also multiplied! Check it out!

In [2]:
bob_x_share = 2 * 2
alice_x_share = 3 * 2

decrypted_x = bob_x_share + alice_x_share
decrypted_x

10

This even works for addition between two shared values!!



In [3]:
# encrypted "5"
bob_x_share = 2
alice_x_share = 3

# encrypted "7"
bob_y_share = 5
alice_y_share = 2

# encrypted 5 + 7
bob_z_share = bob_x_share + bob_y_share
alice_z_share = alice_x_share + alice_y_share

decrypted_z = bob_z_share + alice_z_share
decrypted_z

12

As you can see, we just added two numbers together while they were still encrypted!!!

One small tweak - notice that since all our numbers are positive, it's possible for each share to reveal a little bit of information about the hidden value, namely, it's always greater than the share. Thus, if Bob has a share "3" then he knows that the encrypted value is at least 3.

This would be quite bad, but can be solved through a simple fix. Decryption happens by summing all the shares together MODULUS some constant. I.e.

In [4]:
x = 5

Q = 23740629843760239486723

bob_x_share = 23552870267 # <- a random number
alice_x_share = Q - bob_x_share + x
alice_x_share

23740629843736686616461

In [5]:
(bob_x_share + alice_x_share) % Q

5

So now, as you can see, both shares are wildly larger than the number being shared, meaning that individual shares no longer leak this inforation. However, all the properties we discussed earlier still hold! (addition, encryption, decryption, etc.)

# Project: Build Methods for Encrypt, Decrypt, and Add
In this project, you must take the lessons we learned in the last section and write general methods for encrypt, decrypt, and add. Store shares for a variable in a tuple like ```x_share = (2,5,7)``` if it has 3 shares.



In [0]:
import random
import numpy as np
# try this project here!
default_Q = 293973345475167247070445277780365744413

def encrypt(x, n_shares=3, Q=default_Q):
  # complete the code here
  return x_shares


def decrypt(x_shares, Q=default_Q):
  # complete the code here
  return x

def add(x_shares, y_shares, Q=default_Q):
  # complete the code here
  return z_shares





In [0]:
# a few simple tests
assert decrypt(encrypt(113))==113
assert decrypt(add(encrypt(5), encrypt(6)))==11

# Project: Fixed Precision Encoding

As you may remember, our goal is to aggregate gradients using this new Secret Sharing technique. However, the protocol we've just explored in the last section uses positive integers. However, our neural network weights are NOT integers. Instead, our weights are decimals (floating point numbers).

Not a huge deal! We just need to use a fixed precision encoding, which lets us do computation over decimal numbers using integers!

In [0]:
# complete the following code
import random
import numpy as np

BASE = 10

PRECISION_INTEGRAL = 8
PRECISION_FRACTIONAL = 8

PRECISION = PRECISION_INTEGRAL + PRECISION_FRACTIONAL

#default_Q = 293973345475167247070445277780365744413
assert(default_Q > BASE**PRECISION)

# note that a rational might be negative
# encode and decode rationals to field_element
def encode(rational, Q=default_Q):
    # complete code here
    return field_element

def decode(field_element, Q=default_Q):
    # complete code here
    return rational


In [0]:
# testing
x = encrypt(encode(5.5))
y = encrypt(encode(2.3))
z = add(x,y)
decode(decrypt(z))

[157261321043261917823065844237599434634,
 132977400494673236547132219369279939003,
 3734623937232092700247214174036370776]

# Lesson: Encrypted Subtraction and Public/Scalar Multiplication

In [0]:
field = 23740629843760239486723

In [0]:
x = 5

bob_x_share = 2372385723 # random number
alices_x_share = field - bob_x_share + x

In [0]:
(bob_x_share + alices_x_share) % field

5

In [0]:
field = 10

x = 5

bob_x_share = 8
alice_x_share = field - bob_x_share + x

y = 1

bob_y_share = 9
alice_y_share = field - bob_y_share + y

In [0]:
((bob_x_share + alice_x_share) - (bob_y_share + alice_y_share)) % field

4

In [0]:
((bob_x_share - bob_y_share) + (alice_x_share - alice_y_share)) % field

4

In [0]:
bob_x_share + alice_x_share + bob_y_share + alice_y_share

26

In [0]:
bob_z_share = (bob_x_share - bob_y_share)
alice_z_share = (alice_x_share - alice_y_share)

In [0]:
(bob_z_share + alice_z_share) % field

4

In [0]:
def sub(a, b):
    c = list()
    for i in range(len(a)):
        c.append((a[i] - b[i]) % Q)
    return tuple(c)

In [0]:
field = 10

x = 5

bob_x_share = 8
alice_x_share = field - bob_x_share + x

y = 1

bob_y_share = 9
alice_y_share = field - bob_y_share + y

In [0]:
bob_x_share + alice_x_share

15

In [0]:
bob_y_share + alice_y_share

11

In [0]:
((bob_y_share * 3) + (alice_y_share * 3)) % field

3

In [0]:
def imul(a, scalar):
    
    # logic here which can multiply by a public scalar
    
    c = list()
    
    for i in range(len(a)):
        c.append((a[i] * scalar) % Q)
        
    return tuple(c)

In [0]:
x = encrypt(encode(5.5))
x

[102429626723126324886479814859023395389,
 119121291581510607047487749044084540899,
 72422427170530315136477713877807808125]

In [0]:
z = imul(x, 3)

In [0]:
decode(decrypt(z))

16.5

# Lesson: Encrypted Computation in PySyft

In [7]:
!pip install syft

     |████████████████████████████████| 317kB 4.8MB/s 
     |████████████████████████████████| 81kB 30.7MB/s 
     |████████████████████████████████| 256kB 60.0MB/s 
     |████████████████████████████████| 399kB 50.2MB/s 
     |████████████████████████████████| 204kB 54.6MB/s 
     |████████████████████████████████| 460kB 49.4MB/s 
     |████████████████████████████████| 2.1MB 44.9MB/s 
     |████████████████████████████████| 51kB 21.1MB/s 
     |████████████████████████████████| 266kB 35.5MB/s 
     |████████████████████████████████| 122kB 55.6MB/s 
  Created wheel for zstd: filename=zstd-1.4.3.2-cp36-cp36m-linux_x86_64.whl size=1076270 sha256=b6dcd01351a00793bbd5ac8cc7849ca99cf563d6fde985bb3c62e5a8950454a9
  Stored in directory: /root/.cache/pip/wheels/f2/df/a8/405bafcabba88a18c8763694e79177e2a1bbc65ac0f6b3d728
  Created wheel for pyyaml: filename=PyYAML-5.1.2-cp36-cp36m-linux_x86_64.whl size=44104 sha256=fbf6a0235db4da1899a78604af0ba6542512f952562c9f984b13efaa98cecf62
  Stored in di

In [8]:
import syft as sy
import torch as th
hook = sy.TorchHook(th)
from torch import nn, optim

In [9]:
bob = sy.VirtualWorker(hook, id="bob").add_worker(sy.local_worker)
alice = sy.VirtualWorker(hook, id="alice").add_worker(sy.local_worker)
secure_worker = sy.VirtualWorker(hook, id="secure_worker").add_worker(sy.local_worker)

In [0]:
x = th.tensor([1,2,3,4])
y = th.tensor([2,-1,1,0])

In [0]:
x = x.share(bob, alice, crypto_provider=secure_worker)

In [0]:
y = y.share(bob, alice, crypto_provider=secure_worker)

In [13]:
z = x + y
z.get()

tensor([3, 1, 4, 4])

In [14]:
z = x - y
z.get()

tensor([-1,  3,  2,  4])

In [15]:
z = x * y
z.get()

tensor([ 2, -2,  3,  0])

In [0]:
z = x > y
z.get()

tensor([0, 1, 1, 1])

In [0]:
z = x < y
z.get()

tensor([1, 0, 0, 0])

In [21]:
z = x == y
z.get()

tensor([0, 0, 0, 0])

In [0]:
x = th.tensor([1,2,3,4])
y = th.tensor([2,-1,1,0])

x = x.fix_precision().share(bob, alice, crypto_provider=secure_worker)
y = y.fix_precision().share(bob, alice, crypto_provider=secure_worker)

In [23]:
z = x + y
z.get().float_precision()

tensor([3., 1., 4., 4.])

In [24]:
z = x - y
z.get().float_precision()

tensor([-1.,  3.,  2.,  4.])

In [25]:
z = x * y
z.get().float_precision()

tensor([ 2., -2.,  3.,  0.])

In [26]:
z = x > y
z.get().float_precision()

tensor([0., 1., 1., 1.])

In [27]:
z = x < y
z.get().float_precision()

tensor([1., 0., 0., 0.])

In [28]:
z = x == y
z.get().float_precision()

tensor([0., 0., 0., 0.])

# Lesson: Encrypted Deep Learning in PyTorch

### Train a Model

In [34]:
from torch import nn
from torch import optim
import torch.nn.functional as F

# A Toy Dataset
data = th.tensor([[0,0],[0,1],[1,0],[1,1.]], requires_grad=True)
target = th.tensor([[0],[0],[1],[1.]], requires_grad=True)

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 20)
        self.fc2 = nn.Linear(20, 1)

    def forward(self, x):
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        return x

# A Toy Model
model = Net()

def train():
    # Training Logic
    opt = optim.SGD(params=model.parameters(),lr=0.1)
    for iter in range(20):

        # 1) erase previous gradients (if they exist)
        opt.zero_grad()

        # 2) make a prediction
        pred = model(data)

        # 3) calculate how much we missed
        loss = ((pred - target)**2).sum()

        # 4) figure out which weights caused us to miss
        loss.backward()

        # 5) change those weights
        opt.step()

        # 6) print our progress
        print(loss.data)
        
train()

tensor(5.3720)
tensor(6.8756)
tensor(4.7913)
tensor(0.6858)
tensor(0.5776)
tensor(0.4886)
tensor(0.3997)
tensor(0.3140)
tensor(0.2406)
tensor(0.1809)
tensor(0.1320)
tensor(0.0868)
tensor(0.0581)
tensor(0.0376)
tensor(0.0229)
tensor(0.0144)
tensor(0.0098)
tensor(0.0064)
tensor(0.0043)
tensor(0.0034)


In [35]:
model(data)

tensor([[-0.0155],
        [ 0.0301],
        [ 1.0066],
        [ 0.9648]], grad_fn=<AddmmBackward>)

## Encrypt the Model and Data

In [0]:
encrypted_model = model.fix_precision().share(alice, bob, crypto_provider=secure_worker)

In [37]:
list(encrypted_model.parameters())

[Parameter containing:
 Parameter>FixedPrecisionTensor>[AdditiveSharingTensor]
 	-> [PointerTensor | me:66121832976 -> alice:89092981489]
 	-> [PointerTensor | me:40891084221 -> bob:91933394550]
 	*crypto provider: secure_worker*, Parameter containing:
 Parameter>FixedPrecisionTensor>[AdditiveSharingTensor]
 	-> [PointerTensor | me:45506384263 -> alice:35430537013]
 	-> [PointerTensor | me:65243024548 -> bob:62721619238]
 	*crypto provider: secure_worker*, Parameter containing:
 Parameter>FixedPrecisionTensor>[AdditiveSharingTensor]
 	-> [PointerTensor | me:78746641473 -> alice:88367938857]
 	-> [PointerTensor | me:43681610 -> bob:41661911252]
 	*crypto provider: secure_worker*, Parameter containing:
 Parameter>FixedPrecisionTensor>[AdditiveSharingTensor]
 	-> [PointerTensor | me:21413317891 -> alice:83891226193]
 	-> [PointerTensor | me:72043443664 -> bob:77151367751]
 	*crypto provider: secure_worker*]

In [0]:
encrypted_data = data.fix_precision().share(alice, bob, crypto_provider=secure_worker)

In [39]:
encrypted_data

(Wrapper)>FixedPrecisionTensor>[AdditiveSharingTensor]
	-> [PointerTensor | me:36376295651 -> alice:55953713933]
	-> [PointerTensor | me:33321302504 -> bob:69393344308]
	*crypto provider: secure_worker*

In [0]:
encrypted_prediction = encrypted_model(encrypted_data)

In [41]:
encrypted_prediction.get().float_precision()

tensor([[-0.0160],
        [ 0.0290],
        [ 1.0040],
        [ 0.9630]])

# Project
Build an secrect sharing scheme for english text. 

In [0]:
import random
import numpy as np
# try this project here!
default_Q = 0 # choose a default Q

def encrypt_text(x, n_shares=3, Q=default_Q):
  # complete the code here
  return x_shares


def decrypt_text(x_shares, Q=default_Q):
  # complete the code here
  return x





In [0]:
# test
text ="""
You may write me down in history

With your bitter, twisted lies,

You may tread me in the very dirt

But still, like dust, I’ll rise.
"""

decrypt_text(encrypt_text(text)) == text